---
name: publish package

on:
  push:
    tags:
      - "v*.*.*"
      - "*.*.*"
    paths-ignore:
      - .github/**

jobs:
  publish:
    name: publish package
    uses: strg-at/github-workflows/.github/workflows/npm-publish.yaml@40e5e035df5e075110b80d1a4fddada304604243 # v2.1.2
    with:
      runner: '["ubuntu-latest"]'
