---
name: publish package

on:
  push:
    tags:
      - "v*.*.*"
      - "*.*.*"
    paths-ignore:
      - .github/**

jobs:
  publish:
    name: publish package
    uses: strg-at/github-workflows/.github/workflows/npm-publish.yaml@0fe68f46762ac650f47d56e8c252c31020b0300f # v2.1.0
    with:
      runner: '["ubuntu-latest"]'
