---
name: publish package

on:
  push:
    tags:
      - "v*.*.*"
      - "*.*.*"
    paths-ignore:
      - .github/**

jobs:
  publish:
    name: publish package
    uses: strg-at/github-workflows/.github/workflows/npm-publish.yaml@a926e99cdc1ed63c432b0c5230ad6c6f1189127a # v2.1.3
    with:
      runner: '["ubuntu-latest"]'
