---
name: publish package

on:
  push:
    tags:
      - "v*.*.*"
      - "*.*.*"
    paths-ignore:
      - .github/**

jobs:
  publish:
    name: publish package
    uses: strg-at/github-workflows/.github/workflows/npm-publish.yaml@e3c78564d7b9baf2231e87d8b0085998ec127252 # v2.1.1
    with:
      runner: '["ubuntu-latest"]'
